# deploy Maven artifacts to Sonatype OSS repo
language: java

jdk:
  - openjdk7
  - oraclejdk8

# checkout settings
before_install: 
  - "git clone -b master https://github.com/molindo/travis-settings.git target/travis-settings"
  - "target/travis-settings/tasks/before_install.sh"

# install and deploy
install: "target/travis-settings/tasks/install.sh"
script:  "target/travis-settings/tasks/script.sh"

# travis encrypt 'token@room'
notifications:
  email: false
  hipchat: 
    rooms:
      - secure: "eOySHvqBhpe/O27fT+josVo7lHJ+hfZWQ3/OWrvHBlK0xCBBOlFp3ThGHAiJ8RIT1lm3WolmFS4DYOvyyHGDJed73QZyzdWhKsr26TnBxx65O8ll/FT6TDUj8sV4CjxsAcCpVYSB0j7z3VQXcNH1uev9/+05igg6XN80D4dLDoo="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
    on_success: always
    on_failure: always

# travis encrypt 'CI_DEPLOY_USERNAME=username'
# travis encrypt 'CI_DEPLOY_PASSWORD=password'
env:
  global:
    - secure: "VdQPgGNvEM7LQ436KY18ms/fcnAARSEKOhepjm++giQQ+ivuVi14F6N0wFIm2hksd5iRClkHxwyue+z9nMNQnqDWM7iXGgJeAk6fiXFQYEO9eqGEeXjE1RHbpwFLS55vrD9EG0VHL2skqnVCPvc7QtYoMmMLfzduxgTtkTURnF8="
    - secure: "camNZKc8xlw1M6E2EEW4sLKSSfKMgVHrI774bd2m8gdMiwn0kX/XxV8jUzCl07C3jvC9dlqWZ7qtlFa/P6f7iJnw8CnOo+ta21FrmF97CYqEDjfLKHPj3itIXiQTYHvZnPl2Y1G6MnLmM/pTKFurBxWoe4iKD/rvgPq/BGEA7hk="
